Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "id"
          "AttributeType": "S"
        - "AttributeName": "customerID"
          "AttributeType": " S"
      "KeySchema":
        - "AttributeName": "id"
          "KeyType": "HASH"
        - "AttributeName": "customerId"
          "KeyType": "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Reservations"
